compinfosite/cmpdetails/urls.py
from django.urls import path

from . import views

app_name='cmpdetails'

urlpatterns = [
    path('', views.index, name='index'),
    path('cmp_details/', views.cmp_details , name='cmp_details'),
    path('<int:comp_id>/',views.emp_details, name='emp_details'),
    path('<int:comp_id>/<int:emp_id>/',views.emp_delete, name='emp_delete'),
    path('<int:comp_id>/<int:emp_id>/emp_update',views.emp_update, name='emp_update'),
    path('<int:emp_id>/emp_update',views.emp_update_save, name='emp_update_save'),
    path('cmp_details/<int:comp_id>/add_new_emp_pg',views.add_new_emp_pg,name='add_new_emp_pg'),
    path('cmp_details/<int:comp_id>/emp_add_new',views.emp_add_new,name='emp_add_new'),
]

compinfosite/compinfosite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('cmpdetails/', include('cmpdetails.urls')),
    path('admin/', admin.site.urls),

]

compinfosite/cmpdetails/models.py
from django.db import models

# Create your models here.


class Company(models.Model):
    comp_id = models.AutoField(primary_key=True)
    comp_name = models.CharField(max_length=100)
    comp_budget = models.IntegerField(default=0)


class Employee(models.Model):
    emp_id = models.AutoField(primary_key=True)
    comp_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    salary = models.IntegerField(default=0)
    status = models.CharField(max_length=10)

compinfosite/cmpdetails/views.py
from django.shortcuts import render
from django.http import HttpResponse ,HttpResponseRedirect
from django.template import loader
from django.db.models import Avg, Max, Min ,Count ,Sum
from django.shortcuts import render
from django.urls import reverse
import logging

from .models import Company, Employee

# Create your views here.
logger = logging.getLogger(__name__)
def index(request):
    return render(request,'cmpdetails/index.html')

def cmp_details(request):
    latest_company_list = Company.objects.order_by('-comp_id')
    context = {
        'latest_company_list': latest_company_list,
    }
    return render(request,'cmpdetails/cmp_details.html',context)

def emp_details(request , comp_id):
    emp_details_list = Employee.objects.filter(comp_id=comp_id,status='Active')

    if emp_details_list.exists():

        comp = Company.objects.get(comp_id=comp_id)
        emp_details_list = emp_details_list.filter(status='Active')
        agg_sal=emp_details_list.aggregate(Max('salary'),Min('salary'),Sum('salary'))

        max_sal = emp_details_list.filter(salary=agg_sal['salary__max'])
        min_sal = emp_details_list.filter(salary=agg_sal['salary__min'])
        op_cost = comp.comp_budget-agg_sal['salary__sum']
        emp_count = emp_details_list.aggregate(Count('emp_id'))
        emp_count = emp_count['emp_id__count']

        context={ 'emp_details_list':emp_details_list,'company':comp,'max_sal':max_sal,'min_sal':min_sal,'opt_cost':op_cost,'emp_count':emp_count,}
        return render(request,'cmpdetails/emp_details.html',context)
    else:
        latest_company_list = Company.objects.order_by('-comp_id')
        context = {
            'latest_company_list': latest_company_list,
            'error_message': "Active employees for the selected company does not exist",
        }
    return render(request, 'cmpdetails/cmp_details.html', context)


def emp_delete(request ,comp_id, emp_id):
    emp = Employee.objects.get(emp_id=emp_id)
    emp.status='Inactive'
    emp.save()
    return HttpResponseRedirect(reverse('cmpdetails:cmp_details'))


def emp_update(request, comp_id, emp_id):
    emp_list= Employee.objects.get(emp_id=emp_id)

    context= {'emp_list':emp_list,}
    return render(request, 'cmpdetails/emp_update.html', context)


def emp_update_save(request, emp_id):
    emp = Employee.objects.get(emp_id=emp_id)
    emp.first_name = request.POST['emp_fname']
    emp.last_name = request.POST['emp_lname']
    emp.salary = request.POST['emp_sal']
    emp.status = request.POST['emp_status']
    emp.save()
    return HttpResponseRedirect(reverse('cmpdetails:emp_details', args=(emp.comp_id.pk,)))

def add_new_emp_pg(request,comp_id):
    context={'comp_id':comp_id,}
    return render(request,'cmpdetails/emp_add_new.html',context)


def emp_add_new(request, comp_id):
    emp_fname = request.POST['emp_fname']
    emp_lname = request.POST['emp_lname']
    emp_sal = request.POST['emp_sal']
    emp_status = request.POST['emp_status']
    comp=Company.objects.get(comp_id=comp_id)
    emp=Employee(first_name=emp_fname, last_name=emp_lname, salary=emp_sal, status=emp_status,comp_id=comp)
    emp.save()
    return HttpResponseRedirect(reverse('cmpdetails:add_new_emp_pg', args=(comp_id,)))

compinfosite/cmpdetails/templates/cmpdetails/cmp_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
             box-sizing: border-box;
           }

       div.head_block {
       background-color :#0C7C8C;
       text-align : center;
       color :Black;
       padding: 30px
       }

       div.left_block {
       background-color :#02B2CB;
       text-align: left;
       float: left;
       height :1000px;
       width : 250px
       }
       span {
        padding : 2px 1px 1px 16px;
        display : block;
        font-size: 25px;
       }
       a.left_nav{
        font-side:20px;
        display: block;
        padding : 2px 1px 1px 16px;
        text-decoration:None;
        color: black;
       }
       div.content {
        padding:2px 1px 1px 16px;
        float : left;
       }

    </style>
    <title> Company details</title>
</head>
<body>


<div class="head_block" >
    <h2> Audit Company</h2>
</div>

<div class="left_block">
<span> Audit List</span>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Company</a>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Employee</a>
    <a href="#" class="left_nav">Transfer Employee</a>
</div>

<div class="content">

<h2> Company List</h2>
{% if latest_company_list %}
    <ul>
    {% for company in latest_company_list %}
        <li><a href="{% url 'cmpdetails:emp_details' company.comp_id %}">{{ company.comp_name }}</a></li>
    {% endfor %}
    </ul>
    <p>{{error_message}}</p>
{% else %}
    <p>No company available</p>
{% endif %}

</div>


</body>
</html>

compinfosite/cmpdetails/templates/cmpdetails/emp_add_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
             box-sizing: border-box;
           }

       div.head_block {
       background-color :#0C7C8C;
       text-align : center;
       color :Black;
       padding: 30px
       }

       div.left_block {
       background-color :#02B2CB;
       text-align: left;
       float: left;
       height :1000px;
       width : 250px
       }
       span {
        padding : 2px 1px 1px 16px;
        display : block;
        font-size: 25px;
       }
       a.left_nav{
        font-side:20px;
        display: block;
        padding : 2px 1px 1px 16px;
        text-decoration:None;
        color: black;
       }
       div.content {
        padding:2px 1px 1px 16px;
        float : left;
       }
       table {

        border-collapse:collapse;
        width: 500px
       }

       th , td {
       border: 1px solid Black;
       text-align:left;
       padding:10px;
       }

    </style>
    <title>Home</title>
</head>
<body>


<div class="head_block" >
    <h2> Audit Company</h2>
</div>

<div class="left_block">
<span> Audit List</span>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Company</a>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Employee</a>
    <a href="#" class="left_nav">Transfer Employee</a>
</div>

<div class="content">
    <h3> Employee details to be updated </h3>
    <form action ="{% url 'cmpdetails:emp_add_new' comp_id %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Salary</th>
                <th>Status</th>
                <th>Edit</th>
            </tr>

            <tr>
                <td><input type="text" name="emp_fname" id="emp_fname" ></td>
                <td><input type="text" name="emp_lname" id="emp_lname" ></td>
                <td><input type="text" name="emp_sal" id="emp_sal" ></td>
                <td><input type="text" name="emp_status" id="emp_status" ></td>
                <td><input type="submit" name="Save" id="emp_save" value="Save" ></td>

            </tr>

        </table>
    </form>
    <a href="{% url 'cmpdetails:emp_details' comp_id %}" name="back" id="Back">Back</a>
</div>


</body>
</html>

compinfosite/cmpdetails/templates/cmpdetails/emp_delupd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
             box-sizing: border-box;
           }

       div.head_block {
       background-color :#0C7C8C;
       text-align : center;
       color :Black;
       padding: 30px
       }

       div.left_block {
       background-color :#02B2CB;
       text-align: left;
       float: left;
       height :1000px;
       width : 250px
       }
       span {
        padding : 2px 1px 1px 16px;
        display : block;
        font-size: 25px;
       }
       a.left_nav{
        font-side:20px;
        display: block;
        padding : 2px 1px 1px 16px;
        text-decoration:None;
        color: black;
       }
       div.content {
        padding:2px 1px 1px 16px;
        float : left;
       }

    </style>
    <title>Home</title>
</head>
<body>


<div class="head_block" >
    <h2> Audit Company</h2>
</div>

<div class="left_block">
<span> Audit List</span>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Company</a>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Employee</a>
    <a href="#" class="left_nav">Transfer Employee</a>
</div>

<div class="content">
    <h3> employee to be updated </h3>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Salary</th>
            <th>Status</th>
            <th>Edit</th>
        </tr>
        <tr>

            <form action="#" id="emp_deactivate" name ="emp_deactivate">
                <td><input type="text">{{ emp.first_name }}</td>

            </form>
        </tr>
    </table>


</div>


</body>
</html>

compinfosite/cmpdetails/templates/cmpdetails/emp_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
             box-sizing: border-box;
           }

       div.head_block {
       background-color :#0C7C8C;
       text-align : center;
       color :Black;
       padding: 30px
       }

       div.left_block {
       background-color :#02B2CB;
       text-align: left;
       float: left;
       height :1000px;
       width : 250px
       }
       span {
        padding : 2px 1px 1px 16px;
        display : block;
        font-size: 25px;
       }
       a.left_nav{
        font-side:20px;
        display: block;
        padding : 2px 1px 1px 16px;
        text-decoration:None;
        color: black;
       }
       div.content {
        padding:2px 1px 1px 16px;
        float : left;
       }
       table {

        border-collapse:collapse;
        width: 500px
       }

       th , td {
       border: 1px solid Black;
       text-align:left;
       padding:10px;
       }

    </style>
    <title>Home</title>
</head>
<body>


<div class="head_block" >
    <h2> Audit Company</h2>
</div>

<div class="left_block">
<span> Audit List</span>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Company</a>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Employee</a>
    <a href="#" class="left_nav">Transfer Employee</a>
</div>

<div class="content">
    <h2>Summary</h2>

    <ul>
        <li> No of Employees in the company : {{emp_count}} </li>
        <p></p>
        <li>Operating Cost of Company: {{opt_cost}}</li>
        <p></p>
        <li>Employee with highest salary :{% for max_sal_emp in max_sal %} {{max_sal_emp.first_name}} , {{max_sal_emp.last_name}}  {% endfor %}</li>
        <p></p>
        <li>Employee with least salary :{% for min_sal_emp in min_sal %} {{min_sal_emp.first_name}} , {{min_sal_emp.last_name}} {% endfor %} </li>
        <p></p>

    </ul>
    <h2>List of employee for {{company.comp_name}} </h2>

{% if emp_details_list %}
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Salary</th>
            <th>Status</th>
            <th>Edit</th>
        </tr>
    {% for emp in emp_details_list %}
        <tr>
            <td>{{emp.first_name}}</td>
            <td>{{emp.last_name}}</td>
            <td>{{emp.salary}}</td>
            <td>{{emp.status}}</td>
            <td>
                <a href="{% url 'cmpdetails:emp_delete' company.comp_id emp.emp_id %}" id="emp_delete" name="emp_delete">Delete</a>
                <a href="{% url 'cmpdetails:emp_update' company.comp_id emp.emp_id %}" id="emp_update" name="emp_update">Update</a>
            </td>
        </tr>
    {% endfor %}
    </table>
    <a href="{% url 'cmpdetails:add_new_emp_pg' company.comp_id %}" name="add_new" id="add_new">Add new</a>
{% else %}
    <p>No employees available</p>
{% endif %}
    <br>

</div>
</body>
<script>


</script>
</html>

compinfosite/cmpdetails/templates/cmpdetails/emp_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
             box-sizing: border-box;
           }

       div.head_block {
       background-color :#0C7C8C;
       text-align : center;
       color :Black;
       padding: 30px
       }

       div.left_block {
       background-color :#02B2CB;
       text-align: left;
       float: left;
       height :1000px;
       width : 250px
       }
       span {
        padding : 2px 1px 1px 16px;
        display : block;
        font-size: 25px;
       }
       a.left_nav{
        font-side:20px;
        display: block;
        padding : 2px 1px 1px 16px;
        text-decoration:None;
        color: black;
       }
       div.content {
        padding:2px 1px 1px 16px;
        float : left;
       }
       table {

        border-collapse:collapse;
        width: 500px
       }

       th , td {
       border: 1px solid Black;
       text-align:left;
       padding:10px;
       }

    </style>
    <title>Home</title>
</head>
<body>


<div class="head_block" >
    <h2> Audit Company</h2>
</div>

<div class="left_block">
<span> Audit List</span>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Company</a>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Employee</a>
    <a href="#" class="left_nav">Transfer Employee</a>
</div>

<div class="content">
    <h3> Employee details to be updated </h3>
    <form action ="{% url 'cmpdetails:emp_update_save' emp_list.emp_id %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Salary</th>
                <th>Status</th>
                <th>Edit</th>
            </tr>

            <tr>
                <td><input type="text" name="emp_fname" id="emp_fname" value="{{emp_list.first_name}}"></td>
                <td><input type="text" name="emp_lname" id="emp_lname" value="{{emp_list.last_name}}"></td>
                <td><input type="text" name="emp_sal" id="emp_sal" value="{{emp_list.salary}}"></td>
                <td><input type="text" name="emp_status" id="emp_status" value="{{emp_list.status}}"></td>
                <td><input type="submit" name="Save" id="emp_save" value="Save" ></td>

            </tr>

        </table>
    </form>

</div>


</body>
</html>

compinfosite/cmpdetails/templates/cmpdetails/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
             box-sizing: border-box;
           }

       div.head_block {
       background-color :#0C7C8C;
       text-align : center;
       color :Black;
       padding: 30px
       }

       div.left_block {
       background-color :#02B2CB;
       text-align: left;
       float: left;
       height :1000px;
       width : 250px
       }
       span {
        padding : 2px 1px 1px 16px;
        display : block;
        font-size: 25px;
       }
       a.left_nav{
        font-side:20px;
        display: block;
        padding : 2px 1px 1px 16px;
        text-decoration:None;
        color: black;
       }
       div.content {
        padding:2px 1px 1px 16px;
        float : left;
       }

    </style>
    <title>Home</title>
</head>
<body>


<div class="head_block" >
    <h2> Audit Company</h2>
</div>

<div class="left_block">
<span> Audit List</span>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Company</a>
    <a href="/cmpdetails/cmp_details" class="left_nav"> Employee</a>
    <a href="#" class="left_nav">Transfer Employee</a>
</div>

<div class="content">
    <h3> Welcome to compamny website</h3>
    <p>This site is accessible only to the employees </p>

</div>


</body>
</html>