Django_REST/dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('cluster/<int:cluster_id>/', views.edit_cluster, name='edit_cluster'),
    path('cluster/<int:cluster_id>/save', views.save_cluster, name='save_cluster'),
    path('REST_API/', views.dashboard_rest, name='dashboard_rest'),
    path('detail/<int:cluster_id>', views.dashboard_detail_rest, name='dashboard_detail_rest'),
    path('cluster_list/', views.ClusterList.as_view(), name='ClusterList'),
    path('cluster_elastic_REST/', views.ClusterElastic.as_view(), name='Clusterelastic'),
    path('cluster_elastic/', views.index_elastic, name='index_elastic'),
    path('cluster_elastic/<int:cluster_id>/', views.edit_cluster_elastic, name='edit_cluster_elastic'),
    path('cluster_elastic/<int:cluster_id>/save', views.save_cluster, name='save_cluster_elastic'),

]

Django_REST/dashboard/models.py
from django.db import models

# Create your models here.


class Cluster(models.Model):
    cluster_id = models.AutoField(primary_key=True)
    cluster_name = models.CharField(max_length=100)
    server_count = models.IntegerField(default=0)

Django_REST/dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect , JsonResponse
from django.urls import reverse
# Create your views here.
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from .serializers import ClusterSerializer
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from rest_framework import mixins
from rest_framework import generics

from .models import Cluster

from elasticsearch import Elasticsearch


def create_index():
    es = Elasticsearch([{'host': 'localhost', 'port': 9200}])
    clusters = Cluster.objects.all()
    for cluster in clusters:
        cluster_id = cluster.cluster_id
        serializer = ClusterSerializer(cluster)
        es.index(index='cluster-index', id=cluster_id, body=serializer.data)


def index(request):
    clusters = Cluster.objects.order_by('-cluster_id')
    context = {'clusters': clusters, }
    return render(request, 'dashboard/index.html', context)


def edit_cluster(request, cluster_id):
    cluster = Cluster.objects.filter(cluster_id=cluster_id)
    clusters = Cluster.objects.order_by('-cluster_id')
    context ={'clusters': clusters, 'cluster_id': cluster_id, }
    return render(request, 'dashboard/index.html', context)


def save_cluster(request, cluster_id):
    cluster = Cluster.objects.get(cluster_id=cluster_id)
    cluster.server_count = request.POST['count']
    cluster.save()
    return HttpResponseRedirect(reverse('dashboard:index'))

@api_view(['GET','POST'])
def dashboard_rest(request):
    if request.method == 'GET':
        cluster = Cluster.objects.all()
        serializer = ClusterSerializer(cluster, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = ClusterSerializer(data=request.data)
        if serializer.is_valid():
            return Response(serializer.data, status= status.HTTP_201_CREATED)
        return JsonResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



@api_view(['GET','PUT','DELETE'])
def dashboard_detail_rest(request, cluster_id):
    try:
        cluster = Cluster.objects.get(cluster_id=cluster_id)
    except Cluster.Does:
        return Response(status=404)

    if request.method == 'GET':
        serializer = ClusterSerializer(cluster)
        return Response(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = ClusterSerializer( cluster,data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        cluster.delete()
        return HttpResponse(status=status.HTTP_400_BAD_REQUEST)


class ClusterList(APIView):
    def get(self,request):
        cluster = Cluster.objects.all()
        serializer = ClusterSerializer(cluster, many=True)
        return Response(serializer.data)

    def post(self,request):
        serializer = ClusterSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)




class ClusterElastic(APIView):
    def get(self,request):
        if es.indices.exists(index="cluster-index"):
            doc = {
                'size': 10000,
                'query': {
                    'match_all': {}
                }
            }
            temp =[]
            res = es.search(index="cluster-index", body=doc)
            for item in res["hits"]["hits"]:
                temp.append(item["_source"])
            context = {"clusters": temp}
            # return render(request, 'dashboard/index.html', context)
            return Response(context)
        else:
            create_index()

    def post(self, request):
        es = Elasticsearch([{'host': 'localhost', 'port': 9200}])
        cluster_id = request.data.cluster_id
        es.index(index='cluster-index', id=cluster_id, body=serializer.data)
        cluster = Cluster.objects.get(cluster_id=cluster_id)
        cluster.server_count = request.POST['count']
        cluster.save()
        return Response(context)
        # return HttpResponseRedirect(reverse('dashboard:Clusterelastic'))


es = Elasticsearch([{'host': 'localhost', 'port': 9200}])


def index_elastic(request):
    if not es.indices.exists(index="cluster-index"):
        create_index()
        # return Response(context)
    doc = {
        'size': 10000,
        'query': {
            'match_all': {}
        }
    }
    temp = []
    res = es.search(index="cluster-index", body=doc)
    for item in res["hits"]["hits"]:
        temp.append(item["_source"])
    context = {"clusters": temp}
    return render(request, 'dashboard/index_elastic.html', context)


def edit_cluster_elastic(request, cluster_id):
    doc = {
        'size': 10000,
        'query': {
            'match_all': {}
        }
    }
    temp = []
    res = es.search(index="cluster-index", body=doc)
    for item in res["hits"]["hits"]:
        temp.append(item["_source"])
    context = {"clusters": temp ,'cluster_id': cluster_id, }
    return render(request, 'dashboard/index_elastic.html', context)


def save_cluster_elastic(request, cluster_id):
    es.index(index='cluster-index', id=cluster_id, body=serializer.data)
    return HttpResponseRedirect(reverse('dashboard:index_elastic'))

Django_REST/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <script src="https://kit.fontawesome.com/16adb1c5db.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .fas {
          cursor: pointer;
          padding-left: 0px;
        }

        .column {
          float: left;
          width: 25%;
          padding: 15px;
        }
        .column.side {
          width: 15%;
          padding: 10px;
          height: 200px;
          background-color: #a5d6a7;
          border: 5px solid white;
        }
        .edit-tools {
        position: absolute;
        top: 6px;
        right: 6px;
    </style>

    <title>Dashboard</title>
</head>
<body>
 <h2> Clusters</h2>
 <a href="{% url 'logout' %}" class ='edit-tools'>logout</a>
{% if clusters %}
    <ul>
    {% for cluster in clusters %}
        {% if cluster.cluster_id == cluster_id %}
            <form action ="{% url 'dashboard:save_cluster' cluster.cluster_id %}" method="post">
            {% csrf_token %}
                <div class="column side">
                    <h3>{{ cluster.cluster_name }}({{cluster.server_count}})</h3>
                    <span>No of servers: </span><input type="text" name="count" id="count" value="{{ cluster.server_count }}"/>
                    <a href="#" onclick="document.forms[0].submit();return false;"><i class="fas fa-check"></i></a>
                    <br/>
                    <br/>
                    <span>CPU :59% </span>
                    <span> Memory : 15% Free</span>
                </div>>
        {% else %}
        <div class="column side">

            <h3>{{ cluster.cluster_name }}({{cluster.server_count}})
            </h3>
                    <span>No of servers :{{cluster.server_count}}</span>
                    {% if user.username == "admin" %}
                        <a href="{% url 'dashboard:edit_cluster' cluster.cluster_id %}"><i class="fas fa-pencil-alt"></i> </a>
                    {% endif %}
                    <br/>
                    <br/>
                    <span>CPU :59% </span>
                    <span> Memory : 15% Free</span>
        </div>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No clusters available</p>
{% endif %}

</body>
</html>

Django_REST/dashboard/templates/dashboard/index_elastic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <script src="https://kit.fontawesome.com/16adb1c5db.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .fas {
          cursor: pointer;
          padding-left: 0px;
        }

        .column {
          float: left;
          width: 25%;
          padding: 15px;
        }
        .column.side {
          width: 15%;
          padding: 10px;
          height: 200px;
          background-color: #a5d6a7;
          border: 5px solid white;
        }
        .edit-tools {
        position: absolute;
        top: 6px;
        right: 6px;
    </style>

    <title>Dashboard</title>
</head>
<body>
 <h2> Clusters</h2>
 <a href="{% url 'logout' %}" class ='edit-tools'>logout</a>
{% if clusters %}
    <ul>
    {% for cluster in clusters %}
        {% if cluster.cluster_id == cluster_id %}
            <form action ="{% url 'dashboard:save_cluster_elastic' cluster.cluster_id %}" method="post">
            {% csrf_token %}
                <div class="column side">
                    <h3>{{ cluster.cluster_name }}({{cluster.server_count}})</h3>
                    <span>No of servers: </span><input type="text" name="count" id="count" value="{{ cluster.server_count }}"/>
                    <a href="#" onclick="document.forms[0].submit();return false;"><i class="fas fa-check"></i></a>
                    <br/>
                    <br/>
                    <span>CPU :59% </span>
                    <span> Memory : 15% Free</span>
                </div>>
        {% else %}
        <div class="column side">

            <h3>{{ cluster.cluster_name }}({{cluster.server_count}})
            </h3>
                    <span>No of servers :{{cluster.server_count}}</span>
                    {% if user.username == "admin" %}
                        <a href="{% url 'dashboard:edit_cluster_elastic' cluster.cluster_id %}"><i class="fas fa-pencil-alt"></i> </a>
                    {% endif %}
                    <br/>
                    <br/>
                    <span>CPU :59% </span>
                    <span> Memory : 15% Free</span>
        </div>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No clusters available</p>
{% endif %}

</body>
</html>

Django_REST/dashboard/templates/dashboard/index_v1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h2> Clusters</h2>
{% if clusters %}
    <ul>
    {% for cluster in clusters %}
        <li>
            {{ cluster.cluster_name }}( {{cluster.server_count}} )
            <a href="{% url 'dashboard:edit_cluster' cluster.cluster_id %}" class="left_nav"> Edit</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No clusters available</p>
{% endif %}

</body>
</html>